service: maintenance
runtime: nodejs18

# specs
env: standard
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
  target_cpu_utilization: 0.95
  max_concurrent_requests: 1000
